import { ReduxProvider } from "@/redux/provider";
import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material";
import theme from "@/app/theme";
import "./globals.css";
import "primeicons/primeicons.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
