import { ReduxProvider } from "@/redux/provider";
import type { Metadata } from "next";
import SideBar from "@/components/sidebar/SideBar";
import Content from "./content";

import "./globals.css";
import "primeicons/primeicons.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <SideBar />
          <Content>{children}</Content>
        </ReduxProvider>
      </body>
    </html>
  );
}
