import { formatDate } from "@/utils";

export const permissions = [
  "Add_Receipt",
  "Add_Receipt",
  "Add_Staff",
  "Edit_Staff",
  "Add_Customer",
  "Edit_Customer",
  "Add_Product",
  "Edit_Product",
  "Add_Organization",
  "Edit_Organization",
  "View_Wallet",
];

export const defaultRoles = [
  {
    id: "",
    name: "Admin",
    permissions,
    createdAt: formatDate(new Date()),
  },
  {
    id: "",
    name: "User",
    permissions,
    createdAt: formatDate(new Date()),
  },
  {
    id: "",
    name: "Staff",
    permissions: [
      "Add_Receipt",
      "Add_Receipt",
      "Add_Customer",
      "Edit_Customer",
      "Add_Product",
      "Edit_Product",
      "View_Wallet",
    ],
    createdAt: formatDate(new Date()),
  },
  {
    id: "",
    name: "Customer",
    permissions: [],
    createdAt: formatDate(new Date()),
  },
];

export const businessServices = [
  "Professional Services",
  "Automotive Services",
  "Construction Services",
  "Healthcare Services",
  "Financial Services",
  "Technology Services",
  "Hospitality Services",
  "Education and Training Services",
  "Real Estate Services",
  "Retail and Wholesale Trade",
  "Legal Services",
  "Accounting Services",
  "Consulting Services",
  "Marketing and Advertising",
  "Human Resources Services",
  "Auto Repair and Maintenance",
  "Car Detailing",
  "Tire Services",
  "Medical Clinics",
  "Dental Clinics",
  "Home Healthcare",
  "Pharmaceutical Services",
  "IT Consulting",
  "Web Design and Development",
  "Software Development",
  "Cybersecurity Services",
  "Financial Planning and Advisory",
  "Investment and Wealth Management",
  "Insurance Services",
  "Tax Preparation and Planning",
  "Banking and Lending",
  "Hotel and Lodging",
  "Restaurants and Food Services",
  "Event Planning and Catering",
  "Travel Agencies",
  "Entertainment Venues",
  "Schools and Educational Institutions",
  "Tutoring and Academic Support",
  "Vocational Training",
  "Professional Development Courses",
  "Property Management",
  "Real Estate Brokerage",
  "Appraisal Services",
  "Property Development",
  "E-commerce",
  "Brick-and-mortar Retail Stores",
  "Wholesale Distribution",
  "Manufacturing",
  "Online Learning Platforms",
];
